### ISSUE TITLE
把文件复制进项目 没有compile 项目

### ISSUE THREAD

**Issue by qq634421026** [hongyangAndroid/AndroidAutoLayout#131]
在5.0以下报这个错 5.0以上都没问题 麻烦洋哥 给看下吧  上线之前突然出这问题了 

 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.incoshare.incopat/com.incoshare.incopat.activity.IndexActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class com.incoshare.incopat.autolayout.AutoLinearLayout
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2306)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2364)
                                                                           at android.app.ActivityThread.access$900(ActivityThread.java:162)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:157)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5387)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class com.incoshare.incopat.autolayout.AutoLinearLayout
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:626)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:470)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
                                                                           at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:359)
                                                                           at android.app.Activity.setContentView(Activity.java:2015)
                                                                           at com.incoshare.incopat.activity.IndexActivity.onCreate(IndexActivity.java:134)
                                                                           at android.app.Activity.performCreate(Activity.java:5431)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2364) 
                                                                           at android.app.ActivityThread.access$900(ActivityThread.java:162) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:157) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5387) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081) 
                                                                           at dalvik.system.NativeStart.main(Native Method) 
                                                                        Caused by: java.lang.reflect.InvocationTargetException
                                                                           at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:600)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:470) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
                                                                           at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:359) 
                                                                           at android.app.Activity.setContentView(Activity.java:2015) 
                                                                           at com.incoshare.incopat.activity.IndexActivity.onCreate(IndexActivity.java:134) 
                                                                           at android.app.Activity.performCreate(Activity.java:5431) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2364) 
                                                                           at android.app.ActivityThread.access$900(ActivityThread.java:162) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:157) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5387) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081) 
                                                                           at dalvik.system.NativeStart.main(Native Method) 
                                                                        Caused by: java.lang.NoClassDefFoundError: com.incoshare.incopat.utils.L
                                                                           at com.incoshare.incopat.config.AutoLayoutConifg.getMetaData(AutoLayoutConifg.java:108)
                                                                           at com.incoshare.incopat.config.AutoLayoutConifg.init(AutoLayoutConifg.java:81)
                                                                           at com.incoshare.incopat.autolayout.AutoLayoutHelper.initAutoLayoutConfig(AutoLayoutHelper.java:113)
                                                                           at com.incoshare.incopat.autolayout.AutoLayoutHelper.<init>(AutoLayoutHelper.java:105)
                                                                           at com.incoshare.incopat.autolayout.AutoLinearLayout.<init>(AutoLinearLayout.java:17)
                                                                           at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:600) 
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:470) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
                                                                           at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:359) 
                                                                           at android.app.Activity.setContentView(Activity.java:2015) 
                                                                           at com.incoshare.incopat.activity.IndexActivity.onCreate(IndexActivity.java:134) 
                                                                           at android.app.Activity.performCreate(Activity.java:5431) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2364) 
                                                                           at android.app.ActivityThread.access$900(ActivityThread.java:162) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:157) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5387) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081) 
                                                                           at dalvik.system.NativeStart.main(Native Method)

**Comment by liuyuttkx** [comment]
您 把您 的XML文件 一起发过来看看




liuyu195@126.com
 
发件人： qq634421026
发送时间： 2016-11-23 19:51
收件人： hongyangAndroid/AndroidAutoLayout
主题： [hongyangAndroid/AndroidAutoLayout] 把文件复制进项目 没有compile 项目 (#131)
在5.0以下报这个错 5.0以上都没问题 麻烦洋哥 给看下吧 上线之前突然出这问题了
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.incoshare.incopat/com.incoshare.incopat.activity.IndexActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class com.incoshare.incopat.autolayout.AutoLinearLayout
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2306)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2364)
at android.app.ActivityThread.access$900(ActivityThread.java:162)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:157)
at android.app.ActivityThread.main(ActivityThread.java:5387)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class com.incoshare.incopat.autolayout.AutoLinearLayout
at android.view.LayoutInflater.createView(LayoutInflater.java:626)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
at android.view.LayoutInflater.inflate(LayoutInflater.java:470)
at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:359)
at android.app.Activity.setContentView(Activity.java:2015)
at com.incoshare.incopat.activity.IndexActivity.onCreate(IndexActivity.java:134)
at android.app.Activity.performCreate(Activity.java:5431)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2364) 
at android.app.ActivityThread.access$900(ActivityThread.java:162) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:157) 
at android.app.ActivityThread.main(ActivityThread.java:5387) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:515) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081) 
at dalvik.system.NativeStart.main(Native Method) 
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.constructNative(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at android.view.LayoutInflater.createView(LayoutInflater.java:600)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:470) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:359) 
at android.app.Activity.setContentView(Activity.java:2015) 
at com.incoshare.incopat.activity.IndexActivity.onCreate(IndexActivity.java:134) 
at android.app.Activity.performCreate(Activity.java:5431) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2364) 
at android.app.ActivityThread.access$900(ActivityThread.java:162) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:157) 
at android.app.ActivityThread.main(ActivityThread.java:5387) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:515) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081) 
at dalvik.system.NativeStart.main(Native Method) 
Caused by: java.lang.NoClassDefFoundError: com.incoshare.incopat.utils.L
at com.incoshare.incopat.config.AutoLayoutConifg.getMetaData(AutoLayoutConifg.java:108)
at com.incoshare.incopat.config.AutoLayoutConifg.init(AutoLayoutConifg.java:81)
at com.incoshare.incopat.autolayout.AutoLayoutHelper.initAutoLayoutConfig(AutoLayoutHelper.java:113)
at com.incoshare.incopat.autolayout.AutoLayoutHelper.(AutoLayoutHelper.java:105)
at com.incoshare.incopat.autolayout.AutoLinearLayout.(AutoLinearLayout.java:17)
at java.lang.reflect.Constructor.constructNative(Native Method) 
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
at android.view.LayoutInflater.createView(LayoutInflater.java:600) 
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:470) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:359) 
at android.app.Activity.setContentView(Activity.java:2015) 
at com.incoshare.incopat.activity.IndexActivity.onCreate(IndexActivity.java:134) 
at android.app.Activity.performCreate(Activity.java:5431) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2364) 
at android.app.ActivityThread.access$900(ActivityThread.java:162) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:157) 
at android.app.ActivityThread.main(ActivityThread.java:5387) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:515) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081) 
at dalvik.system.NativeStart.main(Native Method)
